/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as NewLaunchesRouteImport } from './routes/new-launches'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesManufacturingRouteImport } from './routes/services.manufacturing'
import { Route as ServicesMaintenanceRouteImport } from './routes/services.maintenance'
import { Route as ServicesInstallationRouteImport } from './routes/services.installation'
import { Route as ProductsCategoryRouteImport } from './routes/products.$category'
import { Route as BlogFanMaintenanceChecklistRouteImport } from './routes/blog.fan-maintenance-checklist'
import { Route as BlogChooseIndustrialFanSizeRouteImport } from './routes/blog.choose-industrial-fan-size'
import { Route as BlogBldcVsConventionalFansRouteImport } from './routes/blog.bldc-vs-conventional-fans'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ProductsCategoryIndexRouteImport } from './routes/products.$category.index'
import { Route as ProductsCategoryModelRouteImport } from './routes/products.$category.$model'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const NewLaunchesRoute = NewLaunchesRouteImport.update({
  id: '/new-launches',
  path: '/new-launches',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ServicesManufacturingRoute = ServicesManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMaintenanceRoute = ServicesMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInstallationRoute = ServicesInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ProductsRoute,
} as any)
const BlogFanMaintenanceChecklistRoute =
  BlogFanMaintenanceChecklistRouteImport.update({
    id: '/fan-maintenance-checklist',
    path: '/fan-maintenance-checklist',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogChooseIndustrialFanSizeRoute =
  BlogChooseIndustrialFanSizeRouteImport.update({
    id: '/choose-industrial-fan-size',
    path: '/choose-industrial-fan-size',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogBldcVsConventionalFansRoute =
  BlogBldcVsConventionalFansRouteImport.update({
    id: '/bldc-vs-conventional-fans',
    path: '/bldc-vs-conventional-fans',
    getParentRoute: () => BlogRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsCategoryIndexRoute = ProductsCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsCategoryRoute,
} as any)
const ProductsCategoryModelRoute = ProductsCategoryModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => ProductsCategoryRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/gallery': typeof GalleryRoute
  '/mcp': typeof McpRoute
  '/new-launches': typeof NewLaunchesRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/bldc-vs-conventional-fans': typeof BlogBldcVsConventionalFansRoute
  '/blog/choose-industrial-fan-size': typeof BlogChooseIndustrialFanSizeRoute
  '/blog/fan-maintenance-checklist': typeof BlogFanMaintenanceChecklistRoute
  '/products/$category': typeof ProductsCategoryRouteWithChildren
  '/services/installation': typeof ServicesInstallationRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/manufacturing': typeof ServicesManufacturingRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/products/$category/$model': typeof ProductsCategoryModelRoute
  '/products/$category/': typeof ProductsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/gallery': typeof GalleryRoute
  '/mcp': typeof McpRoute
  '/new-launches': typeof NewLaunchesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/bldc-vs-conventional-fans': typeof BlogBldcVsConventionalFansRoute
  '/blog/choose-industrial-fan-size': typeof BlogChooseIndustrialFanSizeRoute
  '/blog/fan-maintenance-checklist': typeof BlogFanMaintenanceChecklistRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/manufacturing': typeof ServicesManufacturingRoute
  '/blog': typeof BlogIndexRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/products/$category/$model': typeof ProductsCategoryModelRoute
  '/products/$category': typeof ProductsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/gallery': typeof GalleryRoute
  '/mcp': typeof McpRoute
  '/new-launches': typeof NewLaunchesRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/bldc-vs-conventional-fans': typeof BlogBldcVsConventionalFansRoute
  '/blog/choose-industrial-fan-size': typeof BlogChooseIndustrialFanSizeRoute
  '/blog/fan-maintenance-checklist': typeof BlogFanMaintenanceChecklistRoute
  '/products/$category': typeof ProductsCategoryRouteWithChildren
  '/services/installation': typeof ServicesInstallationRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/manufacturing': typeof ServicesManufacturingRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/products/$category/$model': typeof ProductsCategoryModelRoute
  '/products/$category/': typeof ProductsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/downloads'
    | '/gallery'
    | '/mcp'
    | '/new-launches'
    | '/products'
    | '/services'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/bldc-vs-conventional-fans'
    | '/blog/choose-industrial-fan-size'
    | '/blog/fan-maintenance-checklist'
    | '/products/$category'
    | '/services/installation'
    | '/services/maintenance'
    | '/services/manufacturing'
    | '/blog/'
    | '/products/'
    | '/services/'
    | '/.mcp/invoke-tool/$tool'
    | '/products/$category/$model'
    | '/products/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/downloads'
    | '/gallery'
    | '/mcp'
    | '/new-launches'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/bldc-vs-conventional-fans'
    | '/blog/choose-industrial-fan-size'
    | '/blog/fan-maintenance-checklist'
    | '/services/installation'
    | '/services/maintenance'
    | '/services/manufacturing'
    | '/blog'
    | '/products'
    | '/services'
    | '/.mcp/invoke-tool/$tool'
    | '/products/$category/$model'
    | '/products/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/downloads'
    | '/gallery'
    | '/mcp'
    | '/new-launches'
    | '/products'
    | '/services'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/bldc-vs-conventional-fans'
    | '/blog/choose-industrial-fan-size'
    | '/blog/fan-maintenance-checklist'
    | '/products/$category'
    | '/services/installation'
    | '/services/maintenance'
    | '/services/manufacturing'
    | '/blog/'
    | '/products/'
    | '/services/'
    | '/.mcp/invoke-tool/$tool'
    | '/products/$category/$model'
    | '/products/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  GalleryRoute: typeof GalleryRoute
  McpRoute: typeof McpRoute
  NewLaunchesRoute: typeof NewLaunchesRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-launches': {
      id: '/new-launches'
      path: '/new-launches'
      fullPath: '/new-launches'
      preLoaderRoute: typeof NewLaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/services/manufacturing': {
      id: '/services/manufacturing'
      path: '/manufacturing'
      fullPath: '/services/manufacturing'
      preLoaderRoute: typeof ServicesManufacturingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/maintenance': {
      id: '/services/maintenance'
      path: '/maintenance'
      fullPath: '/services/maintenance'
      preLoaderRoute: typeof ServicesMaintenanceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/installation': {
      id: '/services/installation'
      path: '/installation'
      fullPath: '/services/installation'
      preLoaderRoute: typeof ServicesInstallationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/blog/fan-maintenance-checklist': {
      id: '/blog/fan-maintenance-checklist'
      path: '/fan-maintenance-checklist'
      fullPath: '/blog/fan-maintenance-checklist'
      preLoaderRoute: typeof BlogFanMaintenanceChecklistRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/choose-industrial-fan-size': {
      id: '/blog/choose-industrial-fan-size'
      path: '/choose-industrial-fan-size'
      fullPath: '/blog/choose-industrial-fan-size'
      preLoaderRoute: typeof BlogChooseIndustrialFanSizeRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/bldc-vs-conventional-fans': {
      id: '/blog/bldc-vs-conventional-fans'
      path: '/bldc-vs-conventional-fans'
      fullPath: '/blog/bldc-vs-conventional-fans'
      preLoaderRoute: typeof BlogBldcVsConventionalFansRouteImport
      parentRoute: typeof BlogRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category/': {
      id: '/products/$category/'
      path: '/'
      fullPath: '/products/$category/'
      preLoaderRoute: typeof ProductsCategoryIndexRouteImport
      parentRoute: typeof ProductsCategoryRoute
    }
    '/products/$category/$model': {
      id: '/products/$category/$model'
      path: '/$model'
      fullPath: '/products/$category/$model'
      preLoaderRoute: typeof ProductsCategoryModelRouteImport
      parentRoute: typeof ProductsCategoryRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogBldcVsConventionalFansRoute: typeof BlogBldcVsConventionalFansRoute
  BlogChooseIndustrialFanSizeRoute: typeof BlogChooseIndustrialFanSizeRoute
  BlogFanMaintenanceChecklistRoute: typeof BlogFanMaintenanceChecklistRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogBldcVsConventionalFansRoute: BlogBldcVsConventionalFansRoute,
  BlogChooseIndustrialFanSizeRoute: BlogChooseIndustrialFanSizeRoute,
  BlogFanMaintenanceChecklistRoute: BlogFanMaintenanceChecklistRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProductsCategoryRouteChildren {
  ProductsCategoryModelRoute: typeof ProductsCategoryModelRoute
  ProductsCategoryIndexRoute: typeof ProductsCategoryIndexRoute
}

const ProductsCategoryRouteChildren: ProductsCategoryRouteChildren = {
  ProductsCategoryModelRoute: ProductsCategoryModelRoute,
  ProductsCategoryIndexRoute: ProductsCategoryIndexRoute,
}

const ProductsCategoryRouteWithChildren =
  ProductsCategoryRoute._addFileChildren(ProductsCategoryRouteChildren)

interface ProductsRouteChildren {
  ProductsCategoryRoute: typeof ProductsCategoryRouteWithChildren
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsCategoryRoute: ProductsCategoryRouteWithChildren,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesInstallationRoute: typeof ServicesInstallationRoute
  ServicesMaintenanceRoute: typeof ServicesMaintenanceRoute
  ServicesManufacturingRoute: typeof ServicesManufacturingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesInstallationRoute: ServicesInstallationRoute,
  ServicesMaintenanceRoute: ServicesMaintenanceRoute,
  ServicesManufacturingRoute: ServicesManufacturingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  GalleryRoute: GalleryRoute,
  McpRoute: McpRoute,
  NewLaunchesRoute: NewLaunchesRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
